name: Deploy Terraform & Lambda

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      action:
        description: "Apply or Destroy Terraform"
        required: true
        default: "apply"
        type: choice
        options:
          - apply
          - destroy

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: |
      (github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'apply') ||
      (github.event_name == 'push' && !contains(github.event.head_commit.message, 'destroy'))
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Create terraform.tfvars
        run: |
           cat <<EOF > terraform/terraform.tfvars
             hosted_zone_id = "${{ secrets.HOSTED_ZONE_ID }}"
             zone_id = "${{ secrets.ZONE_ID }}"
             acm_certificate_arn = "${{ secrets.ACM_CERTIFICTE_ARN }}"
             frontend_domain_name = "${{ secrets.FRONTEND_DOMAIN_NAME }}"
           EOF

      - name: Mask AWS Account ID in Logs
        run: echo "::add-mask::${{ secrets.AWS_ACCOUNT_ID }}"

      - name: Set up Terraform
        run: |
          cd terraform
          terraform init

      - name: Terraform Apply
        run: |
          cd terraform
          terraform apply -auto-approve -var-file=terraform.tfvars

      - name: Deploy Lambda Code
        run: |
          zip -r presign.zip lambda/presign/*
          aws s3 cp presign.zip s3://lambda-code-bucket/
           aws lambda update-function-code --function-name presign --s3-bucket lambda-code-bucket --s3-key presign.zip

      - name: Deploy Frontend to S3
        run: |
          aws s3 sync frontend/ s3://image-resizer.fozdigitalz.com --delete


  destroy:
    runs-on: ubuntu-latest
    if: |
      (github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'destroy') ||
      (github.event_name == 'push' && contains(github.event.head_commit.message, 'destroy'))
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Create terraform.tfvars
        run: |
           cat <<EOF > terraform/terraform.tfvars
             hosted_zone_id = "${{ secrets.HOSTED_ZONE_ID }}"
             acm_certificate_arn = "${{ secrets.ACM_CERTIFICTE_ARN }}"
             frontend_domain_name = "${{ secrets.FRONTEND_DOMAIN_NAME }}"
           EOF

      - name: Mask AWS Account ID in Logs
        run: echo "::add-mask::${{ secrets.AWS_ACCOUNT_ID }}"    

      - name: Set up Terraform
        run: |
          cd terraform
          terraform init

      - name: Terraform Destroy
        run: |
          cd terraform
          terraform destroy -auto-approve -var-file=terraform.tfvars
